# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8cb43e55367018c060bfce0fb7b812c03662ac2b237120c1560f00c2f8b74f19eab913aa616b64bb042ff919670478ea4aabf13c7ab261ef2dfcc7727ddec3f1

test:
  secret_key_base: f39140a73bdb7245af6b83a5a1c5f4d1078a8a969193a42a38108e3a4f3d97390fcce3e68cfb841bb017cedd50f263411992b9ae8c6a69d27412cfff2e27bd27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
